apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: secrets-managed-cluster
spec:
  object-templates:
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: vsphere-creds
        namespace: equeiroz-prd
      data:
        username: '{{ (fromSecret "openshift-config" "lab7" "username") }}'
        password: '{{ (fromSecret "openshift-config" "lab7" "password") }}'
      type: Opaque
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ssh-private-key
        namespace: equeiroz-prd
      data:
        ssh-privatekey: '{{ (fromSecret "openshift-config" "lab7" "ssh-privatekey") }}'
      type: Opaque
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: pull-secret
        namespace: equeiroz-prd
      data:
        .dockerconfigjson: '{{ (fromSecret "openshift-config" "lab7" "pullSecret") }}'
      type: Opaque
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: vsphere-certs
        namespace: equeiroz-prd
      data:
        name: '{{ (fromSecret "openshift-config" "lab7" "cacertificate") }}'
      type: Opaque           
  remediationAction: enforce
  severity: low